import type { Contact, Product, AnalyticalAccount, AutoAnalyticalModel, Budget } from "./types";

export const MOCK_CONTACTS: Contact[] = [
    {
        id: "1",
        name: "Azure Interior",
        email: "azure@example.com",
        phone: "9876543210",
        type: "customer",
        address: "123 Design Street",
        city: "Ahmedabad",
        state: "Gujarat",
        country: "India",
        pincode: "380001",
        tags: ["B2B", "Interior"],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "2",
        name: "WoodMart Supplies",
        email: "supply@woodmart.com",
        phone: "9123456780",
        type: "vendor",
        address: "45 Timber Road",
        city: "Gandhinagar",
        state: "Gujarat",
        country: "India",
        pincode: "382010",
        tags: ["Raw Material", "Wood"],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Office Chair",
        sku: "FURN-001",
        category: "Office Furniture",
        salesPrice: 4500,
        purchasePrice: 3000,
        unit: "pcs",
        taxRate: 18,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "2",
        name: "Teak Wood Sheet",
        sku: "MAT-001",
        category: "Raw Material",
        salesPrice: 0,
        purchasePrice: 1200,
        unit: "sqft",
        taxRate: 18,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "3",
        name: "Executive Desk",
        sku: "FURN-002",
        category: "Office Furniture",
        salesPrice: 12000,
        purchasePrice: 8000,
        unit: "pcs",
        taxRate: 18,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const MOCK_ANALYTICAL_ACCOUNTS: AnalyticalAccount[] = [
    {
        id: "1",
        code: "ANA-001",
        name: "Furniture Expo 2026",
        description: "Expenses and Revenue for Expo",
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "2",
        code: "ANA-002",
        name: "Deepawali Sale",
        description: "Festival Season Tracking",
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const MOCK_AUTO_ANALYTICAL_MODELS: AutoAnalyticalModel[] = [
    {
        id: "1",
        name: "Office Expenses",
        analyticAccountId: "1",
        analyticAccountName: "Furniture Expo 2026",
        priority: 10,
        productCategory: "Office Furniture",
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "2",
        name: "Vendor Specific",
        analyticAccountId: "2",
        analyticAccountName: "Deepawali Sale",
        priority: 20,
        partnerTag: "Raw Material",
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const MOCK_BUDGETS: Budget[] = [
    {
        id: "1",
        name: "Marketing & Sales Budget 2024",
        analyticalAccountId: "1",
        analyticalAccountName: "Marketing & Sales",
        periodStart: "2024-01-01",
        periodEnd: "2024-12-31",
        plannedAmount: 250000,
        actualAmount: 195000,
        achievementPercentage: 78,
        remainingBalance: 55000,
        revisions: [],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "2",
        name: "IT Infrastructure Budget 2024",
        analyticalAccountId: "2",
        analyticalAccountName: "IT Infrastructure",
        periodStart: "2024-01-01",
        periodEnd: "2024-12-31",
        plannedAmount: 350000,
        actualAmount: 320000,
        achievementPercentage: 91.4,
        remainingBalance: 30000,
        revisions: [],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "3",
        name: "R&D Department Budget 2024",
        analyticalAccountId: "1",
        analyticalAccountName: "R&D Department",
        periodStart: "2024-01-01",
        periodEnd: "2024-12-31",
        plannedAmount: 550000,
        actualAmount: 425000,
        achievementPercentage: 77.3,
        remainingBalance: 125000,
        revisions: [],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "4",
        name: "Office Supplies Budget 2024",
        analyticalAccountId: "2",
        analyticalAccountName: "Office Supplies",
        periodStart: "2024-01-01",
        periodEnd: "2024-12-31",
        plannedAmount: 35000,
        actualAmount: 31500,
        achievementPercentage: 90,
        remainingBalance: 3500,
        revisions: [],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "5",
        name: "Employee Training Budget 2024",
        analyticalAccountId: "1",
        analyticalAccountName: "Employee Training",
        periodStart: "2024-01-01",
        periodEnd: "2024-12-31",
        plannedAmount: 75000,
        actualAmount: 68000,
        achievementPercentage: 90.7,
        remainingBalance: 7000,
        revisions: [],
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];
