import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import { runQuery, getQuery, allQuery } from '../config/database.js';
import emailService from '../services/emailService.js';

// Helper function to generate secure random password
function generateSecurePassword(length = 12) {
  const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*';
  let password = '';
  const randomBytes = crypto.randomBytes(length);
  for (let i = 0; i < length; i++) {
    password += charset[randomBytes[i] % charset.length];
  }
  return password;
}

class AuthController {

  // ============================================================================
  // PUBLIC ADMIN SIGNUP
  // ============================================================================
  async signup(req, res, next) {
    try {
      const { name, loginId, email, password } = req.body;

      // Check if login ID already exists
      const existingUser = await getQuery(
        'SELECT id FROM users WHERE login_id = ?',
        [loginId]
      );

      if (existingUser) {
        return res.status(400).json({ error: 'Login ID already exists' });
      }

      // Check if email already exists
      const existingEmail = await getQuery(
        'SELECT id FROM users WHERE email = ?',
        [email]
      );

      if (existingEmail) {
        return res.status(400).json({ error: 'Email already exists' });
      }

      const hashedPassword = await bcrypt.hash(password, 10);

      // Create the first admin user
      const result = await runQuery(
        `INSERT INTO users (login_id, email, password_hash, full_name, role, active)
         VALUES (?, ?, ?, ?, 'admin', 1)`,
        [loginId, email, hashedPassword, name]
      );

      res.status(201).json({
        message: 'Admin account created successfully',
        user: {
          id: result.lastID,
          loginId,
          email,
          name,
          role: 'admin'
        }
      });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // ADMIN USER REGISTRATION (Admin creates new Admin or Portal user)
  // ============================================================================
  async register(req, res, next) {
    try {
      const { name, loginId, email, password, role, contact_id, sendCredentials = true } = req.body;

      // Auto-generate password if not provided (for both admin and portal users)
      let userPassword = password;
      const isAutoGeneratedPassword = !password;
      if (isAutoGeneratedPassword) {
        userPassword = generateSecurePassword(12);
      }

      // Check if login ID already exists
      const existingUser = await getQuery(
        'SELECT id FROM users WHERE login_id = ?',
        [loginId]
      );

      if (existingUser) {
        return res.status(400).json({ error: 'Login ID already exists' });
      }

      // Check if email already exists
      const existingEmail = await getQuery(
        'SELECT id FROM users WHERE email = ?',
        [email]
      );

      if (existingEmail) {
        return res.status(400).json({ error: 'Email already exists' });
      }

      const hashedPassword = await bcrypt.hash(userPassword, 10);

      if (role === 'admin') {
        // Create admin user
        const result = await runQuery(
          `INSERT INTO users (login_id, email, password_hash, full_name, role)
           VALUES (?, ?, ?, ?, ?)`,
          [loginId, email, hashedPassword, name, 'admin']
        );

        // Send email with credentials if requested
        let emailStatus = { sent: false, error: null };
        if (sendCredentials) {
          try {
            await emailService.sendPortalCredentials({
              to: email,
              name: name,
              loginId: loginId,
              email: email,
              password: userPassword,
              portalUrl: process.env.PORTAL_URL || 'http://localhost:5173'
            });
            emailStatus.sent = true;
            console.log(`✅ Admin credentials email sent to ${email}`);
          } catch (emailError) {
            console.error(`❌ Failed to send admin credentials email to ${email}:`, emailError.message);
            emailStatus.error = emailError.message;
          }
        }

        res.status(201).json({
          message: 'Admin user created successfully',
          user: {
            id: result.id,
            loginId,
            email,
            name,
            role: 'admin'
          },
          emailSent: emailStatus.sent,
          ...(emailStatus.error && { emailError: 'Failed to send credentials email. Please provide credentials manually.' })
        });
      } else if (role === 'portal') {
        // For portal users, we need a contact
        let contactId = contact_id;

        if (!contactId) {
          // Create a new contact for this portal user
          const contactResult = await runQuery(
            `INSERT INTO contacts (name, email, contact_type, is_customer, created_by)
             VALUES (?, ?, 'individual', 1, ?)`,
            [name, email, req.user.id]
          );
          contactId = contactResult.id;
        } else {
          // Verify contact exists
          const contact = await getQuery('SELECT id, name, email FROM contacts WHERE id = ?', [contactId]);
          if (!contact) {
            return res.status(404).json({ error: 'Contact not found' });
          }

          // Check if contact already has a user account
          const existingAccess = await getQuery(
            'SELECT id FROM users WHERE contact_id = ?',
            [contactId]
          );
          if (existingAccess) {
            return res.status(400).json({ error: 'Contact already has a user account' });
          }
        }

        // Create portal user
        const result = await runQuery(
          `INSERT INTO users (login_id, email, password_hash, full_name, role, contact_id)
           VALUES (?, ?, ?, ?, ?, ?)`,
          [loginId, email, hashedPassword, name, 'portal', contactId]
        );

        // Send email with credentials if requested
        let emailStatus = { sent: false, error: null };
        if (sendCredentials) {
          try {
            await emailService.sendPortalCredentials({
              to: email,
              name: name,
              loginId: loginId,
              email: email,
              password: userPassword, // Send the plain password (before hashing)
              portalUrl: process.env.PORTAL_URL || 'http://localhost:5173'
            });
            emailStatus.sent = true;
            console.log(`✅ Credentials email sent to ${email}`);
          } catch (emailError) {
            console.error(`❌ Failed to send credentials email to ${email}:`, emailError.message);
            emailStatus.error = emailError.message;
            // Don't fail user creation if email fails
          }
        }

        res.status(201).json({
          message: 'Portal user created successfully',
          user: {
            id: result.id,
            loginId,
            email,
            name,
            role: 'portal',
            contact_id: contactId
          },
          emailSent: emailStatus.sent,
          ...(emailStatus.error && { emailError: 'Failed to send credentials email. Please provide credentials manually.' })
        });
      }
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // UNIFIED LOGIN (Auto-detects Admin or Portal user)
  // ============================================================================
  async login(req, res, next) {
    try {
      const { loginId, password } = req.body;

      // Check users table by login_id or email
      let user = await getQuery(
        'SELECT * FROM users WHERE login_id = ? AND active = 1',
        [loginId]
      );

      // If not found by login_id, try email
      if (!user) {
        user = await getQuery(
          'SELECT * FROM users WHERE email = ? AND active = 1',
          [loginId]
        );
      }

      if (!user) {
        return res.status(401).json({ error: 'Invalid Login ID or Password' });
      }

      // Verify password
      const isPasswordValid = await bcrypt.compare(password, user.password_hash);

      if (!isPasswordValid) {
        return res.status(401).json({ error: 'Invalid Login ID or Password' });
      }

      // Get contact name if portal user
      let contactName = user.full_name;
      if (user.role === 'portal' && user.contact_id) {
        const contact = await getQuery('SELECT name FROM contacts WHERE id = ?', [user.contact_id]);
        if (contact) {
          contactName = contact.name;
        }
      }

      // Generate token with appropriate payload
      const tokenPayload = user.role === 'portal'
        ? { userId: user.id, role: user.role, contactId: user.contact_id }
        : { userId: user.id, role: user.role };

      const token = jwt.sign(
        tokenPayload,
        process.env.JWT_SECRET,
        { expiresIn: process.env.JWT_EXPIRE }
      );

      // Update last login
      await runQuery(
        'UPDATE users SET last_login = datetime(\'now\'), updated_at = datetime(\'now\') WHERE id = ?',
        [user.id]
      );

      return res.json({
        message: 'Login successful',
        token,
        user: {
          id: user.id,
          loginId: user.login_id,
          email: user.email,
          name: contactName,
          role: user.role,
          ...(user.contact_id && { contact_id: user.contact_id })
        }
      });

    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // CREATE PORTAL ACCESS FOR EXISTING CONTACT (DEPRECATED - Use register instead)
  // ============================================================================
  async createPortalAccess(req, res, next) {
    try {
      const { contact_id, loginId, email, password } = req.body;

      const contact = await getQuery('SELECT * FROM contacts WHERE id = ?', [contact_id]);

      if (!contact) {
        return res.status(404).json({ error: 'Contact not found' });
      }

      // Check if login ID already exists
      const existingLoginId = await getQuery(
        'SELECT id FROM users WHERE login_id = ?',
        [loginId]
      );

      if (existingLoginId) {
        return res.status(400).json({ error: 'Login ID already exists' });
      }

      // Check if email already exists
      const existingEmail = await getQuery(
        'SELECT id FROM users WHERE email = ?',
        [email]
      );

      if (existingEmail) {
        return res.status(400).json({ error: 'Email already exists' });
      }

      // Check if contact already has a user account
      const existingAccess = await getQuery(
        'SELECT id FROM users WHERE contact_id = ?',
        [contact_id]
      );

      if (existingAccess) {
        return res.status(400).json({ error: 'Contact already has a user account' });
      }

      const hashedPassword = await bcrypt.hash(password, 10);

      const result = await runQuery(
        `INSERT INTO users (contact_id, login_id, email, password_hash, full_name, role)
         VALUES (?, ?, ?, ?, ?, ?)`,
        [contact_id, loginId, email, hashedPassword, contact.name, 'portal']
      );

      res.status(201).json({
        message: 'Portal access created successfully',
        id: result.id,
        loginId,
        email,
        contact_id
      });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // GET PROFILE
  // ============================================================================
  async getProfile(req, res, next) {
    try {
      const user = await getQuery(
        'SELECT id, login_id as loginId, email, full_name as name, role, created_at FROM users WHERE id = ?',
        [req.user.id]
      );

      res.json({ user });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // UPDATE PASSWORD
  // ============================================================================
  async updatePassword(req, res, next) {
    try {
      const { current_password, new_password } = req.body;

      const user = await getQuery(
        'SELECT * FROM users WHERE id = ?',
        [req.user.id]
      );

      if (!user) {
        return res.status(404).json({ error: 'User not found' });
      }

      const isPasswordValid = await bcrypt.compare(current_password, user.password_hash);

      if (!isPasswordValid) {
        return res.status(401).json({ error: 'Current password is incorrect' });
      }

      const hashedPassword = await bcrypt.hash(new_password, 10);

      await runQuery(
        'UPDATE users SET password_hash = ?, updated_at = datetime(\'now\') WHERE id = ?',
        [hashedPassword, req.user.id]
      );

      res.json({ message: 'Password updated successfully' });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // FORGOT PASSWORD
  // ============================================================================
  async forgotPassword(req, res, next) {
    try {
      const { email } = req.body;

      // Check in users table
      const user = await getQuery('SELECT id, email FROM users WHERE email = ?', [email]);

      if (!user) {
        // Don't reveal if email exists or not for security
        return res.json({ message: 'If an account exists with this email, a password reset link has been sent.' });
      }

      // Generate reset token
      const resetToken = crypto.randomBytes(32).toString('hex');
      const resetTokenHash = crypto.createHash('sha256').update(resetToken).digest('hex');
      const resetTokenExpiry = new Date(Date.now() + 3600000).toISOString(); // 1 hour

      // In a real app, you would:
      // 1. Store the reset token hash and expiry in the database
      // 2. Send an email with the reset link containing the token

      // For now, we'll just log it (replace with email service)
      console.log(`Password reset requested for ${email}. Token: ${resetToken}`);

      res.json({
        message: 'If an account exists with this email, a password reset link has been sent.',
        // Remove this in production - only for testing
        debug_token: process.env.NODE_ENV === 'development' ? resetToken : undefined
      });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // RESET PASSWORD
  // ============================================================================
  async resetPassword(req, res, next) {
    try {
      const { token, password } = req.body;

      // In a real app, you would:
      // 1. Hash the token and look it up in the database
      // 2. Check if it's expired
      // 3. Update the password
      // 4. Invalidate the token

      // For now, this is a placeholder
      res.json({ message: 'Password reset functionality requires email service integration.' });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // LIST ALL USERS (Admin only)
  // ============================================================================
  async listUsers(req, res, next) {
    try {
      // Get all users (both admin and portal)
      const allUsers = await allQuery(
        `SELECT u.id, u.login_id as loginId, u.email, u.full_name as name, u.role, 
                u.active, u.created_at, u.updated_at, u.contact_id,
                c.name as contact_name
         FROM users u
         LEFT JOIN contacts c ON u.contact_id = c.id
         ORDER BY u.created_at DESC`
      );

      // Separate admin and portal users
      const adminUsers = allUsers.filter(u => u.role === 'admin');
      const portalUsers = allUsers.filter(u => u.role === 'portal');

      res.json({
        adminUsers,
        portalUsers,
        total: allUsers.length
      });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // DEACTIVATE USER (Admin only)
  // ============================================================================
  async deactivateUser(req, res, next) {
    try {
      const { id } = req.params;

      // Prevent deactivating yourself
      if (parseInt(id) === req.user.id) {
        return res.status(400).json({ error: 'Cannot deactivate your own account' });
      }

      await runQuery(
        'UPDATE users SET active = 0, updated_at = datetime(\'now\') WHERE id = ?',
        [id]
      );

      res.json({ message: 'User deactivated successfully' });
    } catch (error) {
      next(error);
    }
  }

  // ============================================================================
  // ACTIVATE USER (Admin only)
  // ============================================================================
  async activateUser(req, res, next) {
    try {
      const { id } = req.params;

      await runQuery(
        'UPDATE users SET active = 1, updated_at = datetime(\'now\') WHERE id = ?',
        [id]
      );

      res.json({ message: 'User activated successfully' });
    } catch (error) {
      next(error);
    }
  }
}

export default new AuthController();
