import React, { useState } from 'react';
import { X, Mail, Loader2, CheckCircle2, AlertCircle } from 'lucide-react';
import { Button, Input } from './ui';

interface CreateUserModalProps {
    isOpen: boolean;
    onClose: () => void;
    contactId: number;
    contactName: string;
    contactEmail: string;
    onSuccess: () => void;
}

export const CreateUserModal: React.FC<CreateUserModalProps> = ({
    isOpen,
    onClose,
    contactId,
    contactName,
    contactEmail,
    onSuccess
}) => {
    const [loginId, setLoginId] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState(false);
    const [emailSent, setEmailSent] = useState(false);

    if (!isOpen) return null;

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        setError(null);

        try {
            const token = localStorage.getItem('shiv_auth_token');
            const response = await fetch('http://localhost:5000/api/auth/register', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({
                    name: contactName,
                    loginId: loginId,
                    email: contactEmail,
                    role: 'portal',
                    contact_id: contactId,
                    sendCredentials: true
                    // Password will be auto-generated by backend
                })
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Failed to create user');
            }

            setSuccess(true);
            setEmailSent(data.emailSent || false);

            // Auto-close after 3 seconds
            setTimeout(() => {
                onSuccess();
                onClose();
                resetForm();
            }, 3000);

        } catch (err: any) {
            setError(err.message || 'Failed to create user');
        } finally {
            setLoading(false);
        }
    };

    const resetForm = () => {
        setLoginId('');
        setError(null);
        setSuccess(false);
        setEmailSent(false);
    };

    const handleClose = () => {
        if (!loading) {
            onClose();
            resetForm();
        }
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
                {/* Header */}
                <div className="flex items-center justify-between p-6 border-b">
                    <div>
                        <h2 className="text-xl font-semibold text-gray-900">Create Portal User</h2>
                        <p className="text-sm text-gray-500 mt-1">for {contactName}</p>
                    </div>
                    <button
                        onClick={handleClose}
                        disabled={loading}
                        className="text-gray-400 hover:text-gray-600 transition-colors"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Body */}
                <form onSubmit={handleSubmit} className="p-6 space-y-4">
                    {error && (
                        <div className="p-3 bg-red-50 border border-red-200 rounded-lg flex items-start gap-2">
                            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                            <div className="text-sm text-red-700">{error}</div>
                        </div>
                    )}

                    {success && (
                        <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                            <div className="flex items-center gap-2 text-green-700 mb-2">
                                <CheckCircle2 className="w-5 h-5" />
                                <span className="font-medium">User created successfully!</span>
                            </div>
                            {emailSent ? (
                                <p className="text-sm text-green-600 flex items-center gap-2">
                                    <Mail className="w-4 h-4" />
                                    Credentials sent to {contactEmail}
                                </p>
                            ) : (
                                <p className="text-sm text-amber-600">
                                    ⚠️ User created but email could not be sent. Please provide credentials manually.
                                </p>
                            )}
                        </div>
                    )}

                    {!success && (
                        <>
                            <div>
                                <Input
                                    label="Email"
                                    value={contactEmail}
                                    disabled
                                    className="bg-gray-50"
                                />
                                <p className="text-xs text-gray-500 mt-1">From contact record</p>
                            </div>

                            <div>
                                <Input
                                    label="Login ID *"
                                    placeholder="e.g., customer01"
                                    value={loginId}
                                    onChange={(e) => setLoginId(e.target.value)}
                                    required
                                    disabled={loading}
                                />
                                <p className="text-xs text-gray-500 mt-1">
                                    Unique identifier for login
                                </p>
                            </div>

                            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
                                <p className="text-sm text-blue-700 flex items-center gap-2">
                                    <Mail className="w-4 h-4" />
                                    A secure password will be generated and emailed to the user
                                </p>
                            </div>
                        </>
                    )}
                </form>

                {/* Footer */}
                {!success && (
                    <div className="flex justify-end gap-3 px-6 pb-6">
                        <Button
                            variant="outline"
                            onClick={handleClose}
                            disabled={loading}
                        >
                            Cancel
                        </Button>
                        <Button
                            onClick={handleSubmit}
                            disabled={loading || !loginId.trim()}
                            leftIcon={loading ? <Loader2 className="w-4 h-4 animate-spin" /> : undefined}
                        >
                            {loading ? 'Creating...' : 'Create User & Send Email'}
                        </Button>
                    </div>
                )}
            </div>
        </div>
    );
};
